// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhcwwaprujupyboyzjhz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoY3d3YXBydWp1cHlib3l6amh6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNzI1NTksImV4cCI6MjA2OTk0ODU1OX0.rynZa8WVgGEq-Eso5nCQ-_kyQlR6jBJw_u1RaXlSYTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});